// src/components/ChatArea.jsx
import React, { useRef, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Send, Image as ImageIcon, Loader2 } from 'lucide-react';

export default function ChatArea({ messages, input, setInput, handleSendMessage, isLoading }) {
  const messagesEndRef = useRef(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading]);

  return (
    <div className="flex-1 flex flex-col relative bg-gray-900">
      {/* 채팅 로그 */}
      <div className="flex-1 overflow-y-auto p-4 md:p-8 space-y-6 scrollbar-thin scrollbar-thumb-gray-700">
        
        {/* 'system' 메시지는 화면에 그리지 않습니다. */}
        {messages
          .filter(msg => msg.role !== 'system')
          .map((msg, idx) => (
            <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
              <div className={`max-w-[90%] md:max-w-[70%] p-4 rounded-lg shadow-md leading-relaxed ${
                  msg.role === 'user' ? 'bg-blue-600 text-white rounded-br-none' : 'bg-gray-800 text-gray-200 border border-gray-700 rounded-bl-none'
                }`}>
                
                {msg.role === 'user' ? (
                  msg.content
                ) : (
                  <div className="prose prose-invert prose-sm max-w-none">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>
                      {msg.content}
                    </ReactMarkdown>
                  </div>
                )}
                
                {/* 이미지 표시 로직 */}
                {msg.image ? (
                  <div className="mt-4 rounded-lg overflow-hidden border border-gray-600 animate-in fade-in duration-500">
                     <img src={msg.image} alt="Scene" className="w-full h-auto" />
                     <div className="bg-gray-900 p-2 text-xs text-gray-500 flex items-center gap-1">
                       <ImageIcon size={12}/> generated by AI
                     </div>
                  </div>
                ) : msg.loadingImage ? (
                  // 이미지가 로딩 중일 때 보여줄 UI
                  <div className="mt-4 rounded-lg border border-gray-700 bg-gray-900/50 p-6 flex flex-col items-center justify-center gap-2 text-gray-500 animate-pulse">
                     <Loader2 size={24} className="animate-spin text-yellow-600" />
                     <span className="text-xs">장면을 그리는 중...</span>
                  </div>
                ) : null}

              </div>
            </div>
        ))}
        
        {/* 텍스트 로딩 인디케이터 */}
        {isLoading && (
          <div className="flex justify-start">
            <div className="bg-gray-800 border border-gray-700 text-yellow-500 px-4 py-3 rounded-lg flex items-center gap-3">
               <Loader2 size={18} className="animate-spin" />
               <span className="text-sm font-medium">운명을 계산하는 중...</span>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* 입력창 */}
      <div className="p-4 bg-gray-800 border-t border-gray-700">
        <form onSubmit={handleSendMessage} className="max-w-4xl mx-auto relative flex gap-2">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            disabled={isLoading}
            placeholder="당신의 행동을 서술하세요..."
            className="flex-1 bg-gray-900 border border-gray-600 rounded-lg py-3 px-4 focus:outline-none focus:ring-2 focus:ring-yellow-500 text-white"
          />
          <button type="submit" disabled={!input.trim() || isLoading} className="bg-yellow-600 hover:bg-yellow-700 text-white px-6 rounded-lg font-bold shadow-lg">
            <Send size={18} />
          </button>
        </form>
      </div>
    </div>
  );
}